# Ruff configuration: stricte + complète

# Répertoire de base du code
src = [
    "app"
]

# ✅ Active toutes les règles de lint connues
lint.select = ["ALL"]

# ❌ Désactive celles que tu ne veux vraiment pas (par défaut : vide ici)
lint.ignore = [
    "ANN002",
    "ANN003",
    "BLE001",
    "COM812",
    "D100",
    "D101",  # temporary exclusion. each function needs to be documented
    "D102",  # temporary exclusion. each function needs to be documented
    "D103",  # temporary exclusion. each function needs to be documented
    "D105",  # temporary exclusion. each function needs to be documented
    "D106",  # temporary exclusion. each function needs to be documented
    "D107",  # temporary exclusion. each function needs to be documented
    "D203",
    "D212",
    "EM102",
    "PTH",  # still need to chec if this is useful or not
    "TRY003"
]

# ✅ Fix automatique (optionnel, utile en CI locale)
# fix = true

# ✅ Cible la dernière version stable de Python utilisée
target-version = "py310"

# ✅ Exclut les fichiers générés, migrations, etc.
exclude = [
  ".git",
  ".mypy_cache",
  ".ruff_cache",
  "__pycache__",
  "migrations",
  "tests",
  "**/__init__.py"
]

# ✅ Formattage compatible avec Black (si tu l'utilises)
line-length = 88

